### ISSUE TITLE
Consider adding this Kinesis Freestyle 2 Linux Driver?

### ISSUE THREAD

**Issue by whereswaldon** [bbbbbrie/awesome-kinesis#1]
The multimedia keys on a Kinesis Freestyle 2 do not work on Linux. I've implemented a userspace driver that enables them. It's crude right now, but I'll be continuously be updating it.

You can find the project [here](https://github.com/whereswaldon/kfreestyle2d).

If you only accept more mature, polished work, I understand. I can come back when the driver is more robust.

**Comment by bbbbbrie** [comment]
Fixed!

Thank you very much and happy hacktoberfest! :-)
