### ISSUE TITLE
Has anyone tried to make the USB cable detachable?

### ISSUE THREAD

**Issue by everson** [bbbbbrie/awesome-kinesis#3]
I have other boards I like to switch between from to time to time. And since I try to hide all my cables, I am wondering if there is a way to make this board to have a detachable usb-c connection. Anyone tried it?

**Comment by bbbbbrie** [comment]
Thank you for your interest in this repository. I am going to close this issue because it has been over a year and this is not an issue with the README itself. Have a great day!
